name: 'ZJU-nCov-Hitcarder Action'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            api_key: API_KEY
            secret_key: SECRET_KEY
            dingtalk_token: DINGTALK_TOKEN
            serverchan_key: SERVERCHAN_KEY
    steps:
      - name: Working
        uses: RangeKing/zju-ncov-hitcarder@master
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          API_KEY: ${{ secrets[matrix.api_key] }}
          SECRET_KEY: ${{ secrets[matrix.secret_key] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
          serverchan_key: ${{ secrets[matrix.serverchan_key] }}
